baseURL = "https://gz-default.netlify.com/"
languageCode = "en-us"
theme = "site-theme"
title = "Example"
enableRobotsTXT = true

[params.meta]
description = "This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission."

[[menu.desktop]]
    identifier = "whatweDo"
    name = "What we do"
    url = "/page-1/"
    weight = 1
[[menu.desktop]]
    identifier = "certifications"
    name = "Certifications"
    url = "/page-1/"
    weight = 2
[[menu.desktop]]
    identifier = "contactUs"
    name = "Contact"
    url = "/page-1/"
    weight = 3
[[menu.mobile]]
    identifier = "menu-mobile-1"
    name = "Menu Item 1"
    url = "/page-1"
    weight = 1
        [[menu.mobile]]
            identifier = "menu-child-1"
            name = "Menu Child 1"
            url = "/page-11/"
            weight = 1
            parent = "menu-mobile-1"
[[menu.mobile]]
    identifier = "menu-mobile-2"
    name = "Menu Item 2"
    url = "/page-2"
    weight = 2
[[menu.mobile]]
    identifier = "menu-mobile-3"
    name = "Menu Item 3"
    url = "/page-3"
    weight = 3
[params.contact_numbers]
    Fax = "555.555.5555"
    Phone = "555.555.5555"
[params.Logos]
    color_logo = "/pageimg/branding/MCC.FullMark.Color.svg"
    logo = "/pageimg/branding/MCC.FullMark.White.svg"
    mobile_logo = "/pageimg/example-logo.png"
[params.utility_images]
    thank_you_background = "/pageimg/thank-you-contact.jpg"
[params.address]
    city = "Statesboro"
    state = "GA"
    street = "P.O. Box 134"
    zip = 30459
[params.email]
    email = "example@example.com"
[params.tracking]
    google_analytics = ""
    cloudinaryUrl = ""
[params.social_links]
    facebook = ""
    insta = ""
    linkedin = ""
    pinterest = ""
[params.publishing_settings]
    site_in_production = false

[mediaTypes]
  [mediaTypes."text/noExt"]
    suffixes = ""

[sitemap]
    filename = "sitepages.xml"

[outputFormats]
    [outputFormats.sitemapindex]
        baseName = "sitemapindex"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.sitepages]
        baseName = "sitepages"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.siteposts]
        baseName = "siteposts"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.redirects]
        baseName = "_redirects"
        isPlainText = true
        mediaType = "text/noExt"
        path = "/"
    [outputFormats.Algolia]
        baseName = "algolia"
        isPlainText = true
        mediaType = "application/json"
        notAlternative = true

[outputs]
  home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "redirects", "Algolia"]

[params.algolia]
    appId = ""
    search_key = ""
    index_name = ""

[params.extra_tools]
    algolia_search = false
    font_awesome = true
    floating_header = true