baseURL = "https://mill-creek-construction.netlify.com/"
languageCode = "en-us"
theme = "site-theme"
title = "Mill Creek Construction"
enableRobotsTXT = true

[params.meta]
description = "Mill Creek Construction provides the Southeast United States a comprehensive site work package for a variety of projects. From estimating to field operations, surveying to general contractors, Mill Creek Construction aims to meet the needs of all customers. We are committed to your satisfaction and job quality."

[[menu.desktop]]
    identifier = "whatweDo"
    name = "What we do"
    url = "/services/"
    weight = 1
[[menu.desktop]]
    identifier = "certifications"
    name = "Certifications"
    url = "/certifications/"
    weight = 2
[[menu.desktop]]
    identifier = "contactUs"
    name = "Contact"
    url = "/contact/"
    weight = 3
[[menu.mobile]]
    identifier = "whatweDo"
    name = "What we do"
    url = "/services/"
    weight = 1
[[menu.mobile]]
    identifier = "certifications"
    name = "Certifications"
    url = "/certifications/"
    weight = 2
[[menu.mobile]]
    identifier = "contactUs"
    name = "Contact"
    url = "/contact/"
    weight = 3
[params.contact_numbers]
    Fax = "555.555.5555"
    Phone = "555.555.5555"
[params.Logos]
    color_logo = "/pageimg/branding/MCC.FullMark.Color.svg"
    logo = "/pageimg/branding/MCC.FullMark.White.svg"
    mobile_logo = "/pageimg/branding/MCC.FullMark.White.svg"
[params.utility_images]
    thank_you_background = "/pageimg/thank-you-contact.jpg"
[params.address]
    city = "Statesboro"
    state = "GA"
    street = "P.O. Box 134"
    zip = 30459
[params.email]
    email = "example@example.com"
[params.tracking]
    google_analytics = ""
    cloudinaryUrl = ""
[params.social_links]
    facebook = ""
    insta = ""
    linkedin = ""
    pinterest = ""
[params.publishing_settings]
    site_in_production = false

[mediaTypes]
  [mediaTypes."text/noExt"]
    suffixes = ""

[sitemap]
    filename = "sitepages.xml"

[outputFormats]
    [outputFormats.sitemapindex]
        baseName = "sitemapindex"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.sitepages]
        baseName = "sitepages"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.siteposts]
        baseName = "siteposts"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.redirects]
        baseName = "_redirects"
        isPlainText = true
        mediaType = "text/noExt"
        path = "/"
    [outputFormats.Algolia]
        baseName = "algolia"
        isPlainText = true
        mediaType = "application/json"
        notAlternative = true

[outputs]
  home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "redirects", "Algolia"]

[params.algolia]
    appId = ""
    search_key = ""
    index_name = ""

[params.extra_tools]
    algolia_search = false
    font_awesome = true
    floating_header = true