baseURL = "https://millcreekconstructioncompany.com/"
languageCode = "en-us"
theme = "site-theme"
title = "Mill Creek Construction"
enableRobotsTXT = true

[[menu.desktop]]
    identifier = "What we do"
    name = "What we do"
    url = "/services/"
    weight = 1
[[menu.desktop]]
    identifier = "Certifications"
    name = "Certifications"
    url = "/certifications/"
    weight = 2
[[menu.desktop]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
    weight = 3
[[menu.mobile]]
    identifier = "What we do"
    name = "What we do"
    url = "/services/"
    weight = 1
[[menu.mobile]]
    identifier = "Certifications"
    name = "Certifications"
    url = "/certifications/"
    weight = 2
[[menu.mobile]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
    weight = 3
[[menu.footer]]
    identifier = "What we do"
    name = "What we do"
    url = "/services/"
    weight = 1
[[menu.footer]]
    identifier = "Certifications"
    name = "Certifications"
    url = "/certifications/"
    weight = 2
[[menu.footer]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
    weight = 3
[params.tracking]
    cloudinary_url = "https://res.cloudinary.com/pioneer-design/image/upload"
[params.social_links]
    facebook = ""
    insta = ""
    linkedin = ""
    pinterest = ""
[params.publishing_settings]
    site_in_production = true

[mediaTypes]
  [mediaTypes."text/noExt"]
    suffixes = ""

[sitemap]
    filename = "sitepages.xml"

[outputFormats]
    [outputFormats.sitemapindex]
        baseName = "sitemapindex"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.sitepages]
        baseName = "sitepages"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.siteposts]
        baseName = "siteposts"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.redirects]
        baseName = "_redirects"
        isPlainText = true
        mediaType = "text/noExt"
        path = "/"
    [outputFormats.Algolia]
        baseName = "algolia"
        isPlainText = true
        mediaType = "application/json"
        notAlternative = true

[outputs]
  home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "redirects", "Algolia"]

[params.algolia]
    appId = ""
    search_key = ""
    index_name = ""

[params.extra_tools]
    algolia_search = false
    font_awesome = true
    floating_header = true